exec: [ "/usr/bin/supervisord", "-n" ]
data_sources: [ 'defaults', 'file', 'environment' ]
template_sources: [ file ]
defaults:
  global:
    env_k8sm_http_client_timeout: '5s'
    env_k8sm_state_cache_ttl: '20s'
    env_k8sm_dns_server: '10.10.10.10'
    env_k8sm_dns_domain: 'cluster.local'
    env_k8sm_mesos_executor_cpus: '0.25'
    env_k8sm_mesos_executor_mem: '256'
    env_k8sm_default_container_cpu_limit: '0.25'
    env_k8sm_default_container_mem_limit: '128'
    env_k8sm_proxy_mode: 'iptables'

environments:
  staging:
    bootstrap.sh.erb:
      target: /usr/local/bin/bootstrap.sh
      user: root
      group: root
      perms: 0755
    cloud.cfg.erb:
      target: /var/lib/kubernetes/cloud.cfg
    kube-dns-rc.yaml.erb:
      target: /var/lib/kubernetes/kube-dns-rc.yaml
    kube-dns-svc.yaml.erb:
      target: /var/lib/kubernetes/kube-dns-svc.yaml
    kube-ui-rc.yaml.erb:
      target: /var/lib/kubernetes/kube-ui-rc.yaml
    kube-ui-svc.yaml.erb:
      target: /var/lib/kubernetes/kube-ui-svc.yaml
    supervisord.conf.erb:
      target: /etc/supervisor/conf.d/supervisord.conf
  production:
    bootstrap.sh.erb:
      target: /usr/local/bin/bootstrap.sh
      user: root
      group: root
      perms: 0755
    cloud.cfg.erb:
      target: /var/lib/kubernetes/cloud.cfg
    kube-dns-rc.yaml.erb:
      target: /var/lib/kubernetes/kube-dns-rc.yaml
    kube-dns-svc.yaml.erb:
      target: /var/lib/kubernetes/kube-dns-svc.yaml
    kube-ui-rc.yaml.erb:
      target: /var/lib/kubernetes/kube-ui-rc.yaml
    kube-ui-svc.yaml.erb:
      target: /var/lib/kubernetes/kube-ui-svc.yaml
    supervisord.conf.erb:
      target: /etc/supervisor/conf.d/supervisord.conf
  development:
    bootstrap.sh.erb:
      target: /usr/local/bin/bootstrap.sh
      user: root
      group: root
      perms: 0755
    cloud.cfg.erb:
      target: /var/lib/kubernetes/cloud.cfg
    kube-dns-rc.yaml.erb:
      target: /var/lib/kubernetes/kube-dns-rc.yaml
    kube-dns-svc.yaml.erb:
      target: /var/lib/kubernetes/kube-dns-svc.yaml
    kube-ui-rc.yaml.erb:
      target: /var/lib/kubernetes/kube-ui-rc.yaml
    kube-ui-svc.yaml.erb:
      target: /var/lib/kubernetes/kube-ui-svc.yaml
    supervisord.conf.erb:
      target: /etc/supervisor/conf.d/supervisord.conf